server:
  port: 2000

spring:
  cloud:
    gateway:
      routes:
        - id: userCommandApi
          uri: http://user-command-api:8081/api/v1/users
          predicates:
            - Path=/api/v1/users
        - id: userQueryApi
          uri: http://user-query-api:8082/api/v1/users/**
          predicates:
            - Path=/api/v1/users/**
        - id: bankaccCommandApi
          uri: http://bankacc-command-api:9091/api/v1/bank-accounts
          predicates:
            - Path=/api/v1/bank-accounts
        - id: bankaccQueryApi
          uri: http://bankacc-query-api:9092/api/v1/bank-accounts
          predicates:
            - Path=/api/v1/bank-accounts/**