server:
  port: 9092

axon:
  axonserver:
    servers: axon-server

spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://mysql-container:3306/bank
    username: root
    password: springbankRootPsw
  data:
    mongodb:
      host: mongo-container
      port: 27017
      database: bank

security:
  oauth2:
    resource:
      jwt:
        key-value: bankappsigningkey
